apiVersion: v1
kind: Secret
metadata:
  name: ticketing-api-secret
  namespace: ticketing
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "ticketing_db"

  ConnectionStrings__DefaultConnection: "Host=ticketing-postgres;Port=5432;Database=ticketing_db;Username=postgres;Password=CHANGE_ME"

  JwtSettings__SecretKey: "CHANGE_ME_TO_LONG_RANDOM_SECRET"

  EmailSettings__Username: "CHANGE_ME"
  EmailSettings__Password: "CHANGE_ME"
  EmailSettings__FromEmail: "CHANGE_ME"
