apiVersion: apps/v1
kind : Deployment
metadata : 
  name : ticketing-api
  namespace : ticketing
spec  : 
  replicas : 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector : 
    matchLabels :
      app : ticketing-api
  template :
    metadata :
      labels :
        app : ticketing-api
    spec :
      containers : 
        - name : ticketing-api
          image : ghcr.io/yassin4276/ticketing-api:latest
          ports :
            - containerPort : 8080
          envFrom :
            - configMapRef:
                name: ticketing-api-config
            - secretRef:
                name: ticketing-api-secret
          
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
            