apiVersion: v1
kind: ConfigMap
metadata:
  name: ticketing-api-config
  namespace: ticketing
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  JwtSettings__Issuer: "TicketingAPI"
  JwtSettings__Audience: "TicketingAPIUsers"
  JwtSettings__ExpirationMinutes: "60"
  JwtSettings__RefreshTokenExpiryDays: "7"
  JwtSettings__RefreshTokenAudience: "TicketingAPIRefresh"

  AppUrls__PublicBaseUrl: "http://32.198.44.194"

  EmailSettings__Host: "smtp.gmail.com"
  EmailSettings__Port: "587"
  EmailSettings__FromName: "Ticketing Master"