name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build-test-docker:
    name: Build, Test, and Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build

      - name: Run tests
        run: dotnet test --no-build

      - name: Build Docker image
        run: docker build -t ticketing-api .
      
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/yassin4276/ticketing-api:latest \
            -t ghcr.io/yassin4276/ticketing-api:${{ github.sha }} \
            .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push ghcr.io/yassin4276/ticketing-api:latest
          docker push ghcr.io/yassin4276/ticketing-api:${{ github.sha }}